Style/Documentation:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
